# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - release
  - nightly
notifications:
  email: false

matrix:
    allow_failures:
        - julia: nightly

after_success:
  - julia -e 'cd(Pkg.dir("StateMachineIterators")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("StateMachineIterators"); Pkg.test("StateMachineIterators"; coverage=true)'
